// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.21.12
// source: cmd/enque_downlink.proto

package cmd

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnqueDownlink struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Basestation EUI, 8 bytes little endian
	BsEui uint64 `protobuf:"varint,1,opt,name=bs_eui,json=bsEui,proto3" json:"bs_eui,omitempty"`
	// Endnode EUI, 8 bytes little endian
	EndnodeEui uint64 `protobuf:"varint,2,opt,name=endnode_eui,json=endnodeEui,proto3" json:"endnode_eui,omitempty"`
	// Assigned queue ID for reference
	DlQueId uint64 `protobuf:"varint,3,opt,name=dl_que_id,json=dlQueId,proto3" json:"dl_que_id,omitempty"`
	// Priority, higher values are prioritized, optional, default 0
	Priority *float32 `protobuf:"fixed32,4,opt,name=priority,proto3,oneof" json:"priority,omitempty"`
	// MPF header byte, 1 byte
	Format *uint32 `protobuf:"varint,5,opt,name=format,proto3,oneof" json:"format,omitempty"`
	// Downlink payload.
	//
	// Types that are valid to be assigned to Payload:
	//
	//	*EnqueDownlink_Ack
	//	*EnqueDownlink_Data
	//	*EnqueDownlink_DataEnc
	Payload isEnqueDownlink_Payload `protobuf_oneof:"payload"`
	// True to request End Point response, optional
	ResponseExp *bool `protobuf:"varint,9,opt,name=response_exp,json=responseExp,proto3,oneof" json:"response_exp,omitempty"`
	// True to request priority End Point response, optional
	ResponsePrio *bool `protobuf:"varint,10,opt,name=response_prio,json=responsePrio,proto3,oneof" json:"response_prio,omitempty"`
	// True to request further End Point DL window, optional
	ReqDlWindow *bool `protobuf:"varint,11,opt,name=req_dl_window,json=reqDlWindow,proto3,oneof" json:"req_dl_window,omitempty"`
	// / True to send downlink only if End Point expects a response, optional
	OnlyIfExpected *bool `protobuf:"varint,12,opt,name=only_if_expected,json=onlyIfExpected,proto3,oneof" json:"only_if_expected,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EnqueDownlink) Reset() {
	*x = EnqueDownlink{}
	mi := &file_cmd_enque_downlink_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnqueDownlink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueDownlink) ProtoMessage() {}

func (x *EnqueDownlink) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_enque_downlink_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueDownlink.ProtoReflect.Descriptor instead.
func (*EnqueDownlink) Descriptor() ([]byte, []int) {
	return file_cmd_enque_downlink_proto_rawDescGZIP(), []int{0}
}

func (x *EnqueDownlink) GetBsEui() uint64 {
	if x != nil {
		return x.BsEui
	}
	return 0
}

func (x *EnqueDownlink) GetEndnodeEui() uint64 {
	if x != nil {
		return x.EndnodeEui
	}
	return 0
}

func (x *EnqueDownlink) GetDlQueId() uint64 {
	if x != nil {
		return x.DlQueId
	}
	return 0
}

func (x *EnqueDownlink) GetPriority() float32 {
	if x != nil && x.Priority != nil {
		return *x.Priority
	}
	return 0
}

func (x *EnqueDownlink) GetFormat() uint32 {
	if x != nil && x.Format != nil {
		return *x.Format
	}
	return 0
}

func (x *EnqueDownlink) GetPayload() isEnqueDownlink_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *EnqueDownlink) GetAck() *DownlinkAck {
	if x != nil {
		if x, ok := x.Payload.(*EnqueDownlink_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *EnqueDownlink) GetData() *DownlinkData {
	if x != nil {
		if x, ok := x.Payload.(*EnqueDownlink_Data); ok {
			return x.Data
		}
	}
	return nil
}

func (x *EnqueDownlink) GetDataEnc() *DownlinkDataEncrypted {
	if x != nil {
		if x, ok := x.Payload.(*EnqueDownlink_DataEnc); ok {
			return x.DataEnc
		}
	}
	return nil
}

func (x *EnqueDownlink) GetResponseExp() bool {
	if x != nil && x.ResponseExp != nil {
		return *x.ResponseExp
	}
	return false
}

func (x *EnqueDownlink) GetResponsePrio() bool {
	if x != nil && x.ResponsePrio != nil {
		return *x.ResponsePrio
	}
	return false
}

func (x *EnqueDownlink) GetReqDlWindow() bool {
	if x != nil && x.ReqDlWindow != nil {
		return *x.ReqDlWindow
	}
	return false
}

func (x *EnqueDownlink) GetOnlyIfExpected() bool {
	if x != nil && x.OnlyIfExpected != nil {
		return *x.OnlyIfExpected
	}
	return false
}

type isEnqueDownlink_Payload interface {
	isEnqueDownlink_Payload()
}

type EnqueDownlink_Ack struct {
	// Acknowledgement downlink
	Ack *DownlinkAck `protobuf:"bytes,6,opt,name=ack,proto3,oneof"`
}

type EnqueDownlink_Data struct {
	// Unencrypted payload
	Data *DownlinkData `protobuf:"bytes,7,opt,name=data,proto3,oneof"`
}

type EnqueDownlink_DataEnc struct {
	// Encrypted payload
	DataEnc *DownlinkDataEncrypted `protobuf:"bytes,8,opt,name=data_enc,json=dataEnc,proto3,oneof"`
}

func (*EnqueDownlink_Ack) isEnqueDownlink_Payload() {}

func (*EnqueDownlink_Data) isEnqueDownlink_Payload() {}

func (*EnqueDownlink_DataEnc) isEnqueDownlink_Payload() {}

type DownlinkAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownlinkAck) Reset() {
	*x = DownlinkAck{}
	mi := &file_cmd_enque_downlink_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownlinkAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownlinkAck) ProtoMessage() {}

func (x *DownlinkAck) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_enque_downlink_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownlinkAck.ProtoReflect.Descriptor instead.
func (*DownlinkAck) Descriptor() ([]byte, []int) {
	return file_cmd_enque_downlink_proto_rawDescGZIP(), []int{1}
}

type DownlinkData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// User data
	Data          []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownlinkData) Reset() {
	*x = DownlinkData{}
	mi := &file_cmd_enque_downlink_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownlinkData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownlinkData) ProtoMessage() {}

func (x *DownlinkData) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_enque_downlink_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownlinkData.ProtoReflect.Descriptor instead.
func (*DownlinkData) Descriptor() ([]byte, []int) {
	return file_cmd_enque_downlink_proto_rawDescGZIP(), []int{2}
}

func (x *DownlinkData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type DownlinkDataEncrypted struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Data for each of the m packet counters
	Data [][]byte `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	// Endnode packet counter for which the respective data entry is valid
	PacketCnt     []uint32 `protobuf:"varint,2,rep,packed,name=packet_cnt,json=packetCnt,proto3" json:"packet_cnt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownlinkDataEncrypted) Reset() {
	*x = DownlinkDataEncrypted{}
	mi := &file_cmd_enque_downlink_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownlinkDataEncrypted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownlinkDataEncrypted) ProtoMessage() {}

func (x *DownlinkDataEncrypted) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_enque_downlink_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownlinkDataEncrypted.ProtoReflect.Descriptor instead.
func (*DownlinkDataEncrypted) Descriptor() ([]byte, []int) {
	return file_cmd_enque_downlink_proto_rawDescGZIP(), []int{3}
}

func (x *DownlinkDataEncrypted) GetData() [][]byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *DownlinkDataEncrypted) GetPacketCnt() []uint32 {
	if x != nil {
		return x.PacketCnt
	}
	return nil
}

var File_cmd_enque_downlink_proto protoreflect.FileDescriptor

var file_cmd_enque_downlink_proto_rawDesc = string([]byte{
	0x0a, 0x18, 0x63, 0x6d, 0x64, 0x2f, 0x65, 0x6e, 0x71, 0x75, 0x65, 0x5f, 0x64, 0x6f, 0x77, 0x6e,
	0x6c, 0x69, 0x6e, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x63, 0x6d, 0x64, 0x22,
	0xc0, 0x04, 0x0a, 0x0d, 0x45, 0x6e, 0x71, 0x75, 0x65, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x69, 0x6e,
	0x6b, 0x12, 0x15, 0x0a, 0x06, 0x62, 0x73, 0x5f, 0x65, 0x75, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x05, 0x62, 0x73, 0x45, 0x75, 0x69, 0x12, 0x1f, 0x0a, 0x0b, 0x65, 0x6e, 0x64, 0x6e,
	0x6f, 0x64, 0x65, 0x5f, 0x65, 0x75, 0x69, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x65,
	0x6e, 0x64, 0x6e, 0x6f, 0x64, 0x65, 0x45, 0x75, 0x69, 0x12, 0x1a, 0x0a, 0x09, 0x64, 0x6c, 0x5f,
	0x71, 0x75, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x64, 0x6c,
	0x51, 0x75, 0x65, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x08, 0x70, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74,
	0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x48, 0x01, 0x52, 0x08, 0x70, 0x72, 0x69, 0x6f, 0x72,
	0x69, 0x74, 0x79, 0x88, 0x01, 0x01, 0x12, 0x1b, 0x0a, 0x06, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x02, 0x52, 0x06, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74,
	0x88, 0x01, 0x01, 0x12, 0x24, 0x0a, 0x03, 0x61, 0x63, 0x6b, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x10, 0x2e, 0x63, 0x6d, 0x64, 0x2e, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x69, 0x6e, 0x6b, 0x41,
	0x63, 0x6b, 0x48, 0x00, 0x52, 0x03, 0x61, 0x63, 0x6b, 0x12, 0x27, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x63, 0x6d, 0x64, 0x2e, 0x44, 0x6f,
	0x77, 0x6e, 0x6c, 0x69, 0x6e, 0x6b, 0x44, 0x61, 0x74, 0x61, 0x48, 0x00, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x12, 0x37, 0x0a, 0x08, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x65, 0x6e, 0x63, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x63, 0x6d, 0x64, 0x2e, 0x44, 0x6f, 0x77, 0x6e, 0x6c,
	0x69, 0x6e, 0x6b, 0x44, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x65, 0x64,
	0x48, 0x00, 0x52, 0x07, 0x64, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x63, 0x12, 0x26, 0x0a, 0x0c, 0x72,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x65, 0x78, 0x70, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x08, 0x48, 0x03, 0x52, 0x0b, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x45, 0x78, 0x70,
	0x88, 0x01, 0x01, 0x12, 0x28, 0x0a, 0x0d, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f,
	0x70, 0x72, 0x69, 0x6f, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x08, 0x48, 0x04, 0x52, 0x0c, 0x72, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50, 0x72, 0x69, 0x6f, 0x88, 0x01, 0x01, 0x12, 0x27, 0x0a,
	0x0d, 0x72, 0x65, 0x71, 0x5f, 0x64, 0x6c, 0x5f, 0x77, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x18, 0x0b,
	0x20, 0x01, 0x28, 0x08, 0x48, 0x05, 0x52, 0x0b, 0x72, 0x65, 0x71, 0x44, 0x6c, 0x57, 0x69, 0x6e,
	0x64, 0x6f, 0x77, 0x88, 0x01, 0x01, 0x12, 0x2d, 0x0a, 0x10, 0x6f, 0x6e, 0x6c, 0x79, 0x5f, 0x69,
	0x66, 0x5f, 0x65, 0x78, 0x70, 0x65, 0x63, 0x74, 0x65, 0x64, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x08,
	0x48, 0x06, 0x52, 0x0e, 0x6f, 0x6e, 0x6c, 0x79, 0x49, 0x66, 0x45, 0x78, 0x70, 0x65, 0x63, 0x74,
	0x65, 0x64, 0x88, 0x01, 0x01, 0x42, 0x09, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64,
	0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x70, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x42, 0x09, 0x0a,
	0x07, 0x5f, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x42, 0x0f, 0x0a, 0x0d, 0x5f, 0x72, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x65, 0x78, 0x70, 0x42, 0x10, 0x0a, 0x0e, 0x5f, 0x72, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x70, 0x72, 0x69, 0x6f, 0x42, 0x10, 0x0a, 0x0e, 0x5f,
	0x72, 0x65, 0x71, 0x5f, 0x64, 0x6c, 0x5f, 0x77, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x42, 0x13, 0x0a,
	0x11, 0x5f, 0x6f, 0x6e, 0x6c, 0x79, 0x5f, 0x69, 0x66, 0x5f, 0x65, 0x78, 0x70, 0x65, 0x63, 0x74,
	0x65, 0x64, 0x22, 0x0d, 0x0a, 0x0b, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x69, 0x6e, 0x6b, 0x41, 0x63,
	0x6b, 0x22, 0x22, 0x0a, 0x0c, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x69, 0x6e, 0x6b, 0x44, 0x61, 0x74,
	0x61, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x4a, 0x0a, 0x15, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x69, 0x6e,
	0x6b, 0x44, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x65, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x5f, 0x63, 0x6e, 0x74,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x09, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x43, 0x6e,
	0x74, 0x42, 0x26, 0x5a, 0x24, 0x6d, 0x69, 0x6f, 0x74, 0x79, 0x2d, 0x62, 0x73, 0x73, 0x63, 0x69,
	0x2d, 0x61, 0x64, 0x61, 0x70, 0x74, 0x65, 0x72, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61,
	0x6c, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6d, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
})

var (
	file_cmd_enque_downlink_proto_rawDescOnce sync.Once
	file_cmd_enque_downlink_proto_rawDescData []byte
)

func file_cmd_enque_downlink_proto_rawDescGZIP() []byte {
	file_cmd_enque_downlink_proto_rawDescOnce.Do(func() {
		file_cmd_enque_downlink_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cmd_enque_downlink_proto_rawDesc), len(file_cmd_enque_downlink_proto_rawDesc)))
	})
	return file_cmd_enque_downlink_proto_rawDescData
}

var file_cmd_enque_downlink_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_cmd_enque_downlink_proto_goTypes = []any{
	(*EnqueDownlink)(nil),         // 0: cmd.EnqueDownlink
	(*DownlinkAck)(nil),           // 1: cmd.DownlinkAck
	(*DownlinkData)(nil),          // 2: cmd.DownlinkData
	(*DownlinkDataEncrypted)(nil), // 3: cmd.DownlinkDataEncrypted
}
var file_cmd_enque_downlink_proto_depIdxs = []int32{
	1, // 0: cmd.EnqueDownlink.ack:type_name -> cmd.DownlinkAck
	2, // 1: cmd.EnqueDownlink.data:type_name -> cmd.DownlinkData
	3, // 2: cmd.EnqueDownlink.data_enc:type_name -> cmd.DownlinkDataEncrypted
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_cmd_enque_downlink_proto_init() }
func file_cmd_enque_downlink_proto_init() {
	if File_cmd_enque_downlink_proto != nil {
		return
	}
	file_cmd_enque_downlink_proto_msgTypes[0].OneofWrappers = []any{
		(*EnqueDownlink_Ack)(nil),
		(*EnqueDownlink_Data)(nil),
		(*EnqueDownlink_DataEnc)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cmd_enque_downlink_proto_rawDesc), len(file_cmd_enque_downlink_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cmd_enque_downlink_proto_goTypes,
		DependencyIndexes: file_cmd_enque_downlink_proto_depIdxs,
		MessageInfos:      file_cmd_enque_downlink_proto_msgTypes,
	}.Build()
	File_cmd_enque_downlink_proto = out.File
	file_cmd_enque_downlink_proto_goTypes = nil
	file_cmd_enque_downlink_proto_depIdxs = nil
}
