// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.21.12
// source: cmd/propagate_endnode.proto

package cmd

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PropagateEndnode struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Endnode EUI, 8 bytes little endian
	EndnodeEui uint64 `protobuf:"varint,1,opt,name=endnode_eui,json=endnodeEui,proto3" json:"endnode_eui,omitempty"`
	// Command.
	//
	// Types that are valid to be assigned to Command:
	//
	//	*PropagateEndnode_PrpAtt
	//	*PropagateEndnode_PrpDet
	Command isPropagateEndnode_Command `protobuf_oneof:"command"`
	// Whitelist of basestation EUIs in 8 bytes little endian.
	// Propagate message will be send to only included EUIs.
	// Whitelist takes precedence over blacklist.
	//
	// Empty whitelist and blacklist is broadcast.
	BsWhitelist []uint64 `protobuf:"varint,4,rep,packed,name=bs_whitelist,json=bsWhitelist,proto3" json:"bs_whitelist,omitempty"`
	// Blacklist of basestation EUIs in 8 bytes little endian.
	// Propagate message will be send to all excluded EUIs.
	// Whitelist takes precedence over blacklist.
	//
	// Empty whitelist and blacklist is broadcast.
	BsBlacklist   []uint64 `protobuf:"varint,5,rep,packed,name=bs_blacklist,json=bsBlacklist,proto3" json:"bs_blacklist,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PropagateEndnode) Reset() {
	*x = PropagateEndnode{}
	mi := &file_cmd_propagate_endnode_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PropagateEndnode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PropagateEndnode) ProtoMessage() {}

func (x *PropagateEndnode) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_propagate_endnode_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PropagateEndnode.ProtoReflect.Descriptor instead.
func (*PropagateEndnode) Descriptor() ([]byte, []int) {
	return file_cmd_propagate_endnode_proto_rawDescGZIP(), []int{0}
}

func (x *PropagateEndnode) GetEndnodeEui() uint64 {
	if x != nil {
		return x.EndnodeEui
	}
	return 0
}

func (x *PropagateEndnode) GetCommand() isPropagateEndnode_Command {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *PropagateEndnode) GetPrpAtt() *PropagateAttach {
	if x != nil {
		if x, ok := x.Command.(*PropagateEndnode_PrpAtt); ok {
			return x.PrpAtt
		}
	}
	return nil
}

func (x *PropagateEndnode) GetPrpDet() *PropagateDetach {
	if x != nil {
		if x, ok := x.Command.(*PropagateEndnode_PrpDet); ok {
			return x.PrpDet
		}
	}
	return nil
}

func (x *PropagateEndnode) GetBsWhitelist() []uint64 {
	if x != nil {
		return x.BsWhitelist
	}
	return nil
}

func (x *PropagateEndnode) GetBsBlacklist() []uint64 {
	if x != nil {
		return x.BsBlacklist
	}
	return nil
}

type isPropagateEndnode_Command interface {
	isPropagateEndnode_Command()
}

type PropagateEndnode_PrpAtt struct {
	// Server attachment
	PrpAtt *PropagateAttach `protobuf:"bytes,2,opt,name=prpAtt,proto3,oneof"`
}

type PropagateEndnode_PrpDet struct {
	// Server detachment
	PrpDet *PropagateDetach `protobuf:"bytes,3,opt,name=prpDet,proto3,oneof"`
}

func (*PropagateEndnode_PrpAtt) isPropagateEndnode_Command() {}

func (*PropagateEndnode_PrpDet) isPropagateEndnode_Command() {}

type PropagateAttach struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// End Point short address
	ShAddr uint32 `protobuf:"varint,1,opt,name=sh_addr,json=shAddr,proto3" json:"sh_addr,omitempty"`
	// 16 Byte End Point network session key
	NwkSessionKey []byte `protobuf:"bytes,2,opt,name=nwk_session_key,json=nwkSessionKey,proto3" json:"nwk_session_key,omitempty"`
	// Packet counter.
	LastPacketCnt int32 `protobuf:"varint,3,opt,name=last_packet_cnt,json=lastPacketCnt,proto3" json:"last_packet_cnt,omitempty"`
	// True if End Point is bidirectional
	Bidi bool `protobuf:"varint,4,opt,name=bidi,proto3" json:"bidi,omitempty"`
	// True if End Point uses dual channel mode
	DualChannel bool `protobuf:"varint,5,opt,name=dual_channel,json=dualChannel,proto3" json:"dual_channel,omitempty"`
	// True if End Point uses DL repetition
	Repetition bool `protobuf:"varint,6,opt,name=repetition,proto3" json:"repetition,omitempty"`
	// True if End Point uses wide carrier offset
	WideCarrOff bool `protobuf:"varint,7,opt,name=wide_carr_off,json=wideCarrOff,proto3" json:"wide_carr_off,omitempty"`
	// True if End Point uses long DL interblock distance
	LongBlkDist   bool `protobuf:"varint,8,opt,name=long_blk_dist,json=longBlkDist,proto3" json:"long_blk_dist,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PropagateAttach) Reset() {
	*x = PropagateAttach{}
	mi := &file_cmd_propagate_endnode_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PropagateAttach) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PropagateAttach) ProtoMessage() {}

func (x *PropagateAttach) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_propagate_endnode_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PropagateAttach.ProtoReflect.Descriptor instead.
func (*PropagateAttach) Descriptor() ([]byte, []int) {
	return file_cmd_propagate_endnode_proto_rawDescGZIP(), []int{1}
}

func (x *PropagateAttach) GetShAddr() uint32 {
	if x != nil {
		return x.ShAddr
	}
	return 0
}

func (x *PropagateAttach) GetNwkSessionKey() []byte {
	if x != nil {
		return x.NwkSessionKey
	}
	return nil
}

func (x *PropagateAttach) GetLastPacketCnt() int32 {
	if x != nil {
		return x.LastPacketCnt
	}
	return 0
}

func (x *PropagateAttach) GetBidi() bool {
	if x != nil {
		return x.Bidi
	}
	return false
}

func (x *PropagateAttach) GetDualChannel() bool {
	if x != nil {
		return x.DualChannel
	}
	return false
}

func (x *PropagateAttach) GetRepetition() bool {
	if x != nil {
		return x.Repetition
	}
	return false
}

func (x *PropagateAttach) GetWideCarrOff() bool {
	if x != nil {
		return x.WideCarrOff
	}
	return false
}

func (x *PropagateAttach) GetLongBlkDist() bool {
	if x != nil {
		return x.LongBlkDist
	}
	return false
}

type PropagateDetach struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PropagateDetach) Reset() {
	*x = PropagateDetach{}
	mi := &file_cmd_propagate_endnode_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PropagateDetach) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PropagateDetach) ProtoMessage() {}

func (x *PropagateDetach) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_propagate_endnode_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PropagateDetach.ProtoReflect.Descriptor instead.
func (*PropagateDetach) Descriptor() ([]byte, []int) {
	return file_cmd_propagate_endnode_proto_rawDescGZIP(), []int{2}
}

var File_cmd_propagate_endnode_proto protoreflect.FileDescriptor

var file_cmd_propagate_endnode_proto_rawDesc = string([]byte{
	0x0a, 0x1b, 0x63, 0x6d, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x70, 0x61, 0x67, 0x61, 0x74, 0x65, 0x5f,
	0x65, 0x6e, 0x64, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x63,
	0x6d, 0x64, 0x22, 0xe4, 0x01, 0x0a, 0x10, 0x50, 0x72, 0x6f, 0x70, 0x61, 0x67, 0x61, 0x74, 0x65,
	0x45, 0x6e, 0x64, 0x6e, 0x6f, 0x64, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x65, 0x6e, 0x64, 0x6e, 0x6f,
	0x64, 0x65, 0x5f, 0x65, 0x75, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x65, 0x6e,
	0x64, 0x6e, 0x6f, 0x64, 0x65, 0x45, 0x75, 0x69, 0x12, 0x2e, 0x0a, 0x06, 0x70, 0x72, 0x70, 0x41,
	0x74, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x63, 0x6d, 0x64, 0x2e, 0x50,
	0x72, 0x6f, 0x70, 0x61, 0x67, 0x61, 0x74, 0x65, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x48, 0x00,
	0x52, 0x06, 0x70, 0x72, 0x70, 0x41, 0x74, 0x74, 0x12, 0x2e, 0x0a, 0x06, 0x70, 0x72, 0x70, 0x44,
	0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x63, 0x6d, 0x64, 0x2e, 0x50,
	0x72, 0x6f, 0x70, 0x61, 0x67, 0x61, 0x74, 0x65, 0x44, 0x65, 0x74, 0x61, 0x63, 0x68, 0x48, 0x00,
	0x52, 0x06, 0x70, 0x72, 0x70, 0x44, 0x65, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x62, 0x73, 0x5f, 0x77,
	0x68, 0x69, 0x74, 0x65, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x04, 0x20, 0x03, 0x28, 0x04, 0x52, 0x0b,
	0x62, 0x73, 0x57, 0x68, 0x69, 0x74, 0x65, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x62,
	0x73, 0x5f, 0x62, 0x6c, 0x61, 0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x05, 0x20, 0x03, 0x28,
	0x04, 0x52, 0x0b, 0x62, 0x73, 0x42, 0x6c, 0x61, 0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74, 0x42, 0x09,
	0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x22, 0x99, 0x02, 0x0a, 0x0f, 0x50, 0x72,
	0x6f, 0x70, 0x61, 0x67, 0x61, 0x74, 0x65, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x12, 0x17, 0x0a,
	0x07, 0x73, 0x68, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06,
	0x73, 0x68, 0x41, 0x64, 0x64, 0x72, 0x12, 0x26, 0x0a, 0x0f, 0x6e, 0x77, 0x6b, 0x5f, 0x73, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x0d, 0x6e, 0x77, 0x6b, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x4b, 0x65, 0x79, 0x12, 0x26,
	0x0a, 0x0f, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x5f, 0x63, 0x6e,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x6c, 0x61, 0x73, 0x74, 0x50, 0x61, 0x63,
	0x6b, 0x65, 0x74, 0x43, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x69, 0x64, 0x69, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x62, 0x69, 0x64, 0x69, 0x12, 0x21, 0x0a, 0x0c, 0x64, 0x75,
	0x61, 0x6c, 0x5f, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x0b, 0x64, 0x75, 0x61, 0x6c, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x1e, 0x0a,
	0x0a, 0x72, 0x65, 0x70, 0x65, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x0a, 0x72, 0x65, 0x70, 0x65, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x22, 0x0a,
	0x0d, 0x77, 0x69, 0x64, 0x65, 0x5f, 0x63, 0x61, 0x72, 0x72, 0x5f, 0x6f, 0x66, 0x66, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x77, 0x69, 0x64, 0x65, 0x43, 0x61, 0x72, 0x72, 0x4f, 0x66,
	0x66, 0x12, 0x22, 0x0a, 0x0d, 0x6c, 0x6f, 0x6e, 0x67, 0x5f, 0x62, 0x6c, 0x6b, 0x5f, 0x64, 0x69,
	0x73, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x6c, 0x6f, 0x6e, 0x67, 0x42, 0x6c,
	0x6b, 0x44, 0x69, 0x73, 0x74, 0x22, 0x11, 0x0a, 0x0f, 0x50, 0x72, 0x6f, 0x70, 0x61, 0x67, 0x61,
	0x74, 0x65, 0x44, 0x65, 0x74, 0x61, 0x63, 0x68, 0x42, 0x26, 0x5a, 0x24, 0x6d, 0x69, 0x6f, 0x74,
	0x79, 0x2d, 0x62, 0x73, 0x73, 0x63, 0x69, 0x2d, 0x61, 0x64, 0x61, 0x70, 0x74, 0x65, 0x72, 0x2f,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6d, 0x64,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_cmd_propagate_endnode_proto_rawDescOnce sync.Once
	file_cmd_propagate_endnode_proto_rawDescData []byte
)

func file_cmd_propagate_endnode_proto_rawDescGZIP() []byte {
	file_cmd_propagate_endnode_proto_rawDescOnce.Do(func() {
		file_cmd_propagate_endnode_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cmd_propagate_endnode_proto_rawDesc), len(file_cmd_propagate_endnode_proto_rawDesc)))
	})
	return file_cmd_propagate_endnode_proto_rawDescData
}

var file_cmd_propagate_endnode_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_cmd_propagate_endnode_proto_goTypes = []any{
	(*PropagateEndnode)(nil), // 0: cmd.PropagateEndnode
	(*PropagateAttach)(nil),  // 1: cmd.PropagateAttach
	(*PropagateDetach)(nil),  // 2: cmd.PropagateDetach
}
var file_cmd_propagate_endnode_proto_depIdxs = []int32{
	1, // 0: cmd.PropagateEndnode.prpAtt:type_name -> cmd.PropagateAttach
	2, // 1: cmd.PropagateEndnode.prpDet:type_name -> cmd.PropagateDetach
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_cmd_propagate_endnode_proto_init() }
func file_cmd_propagate_endnode_proto_init() {
	if File_cmd_propagate_endnode_proto != nil {
		return
	}
	file_cmd_propagate_endnode_proto_msgTypes[0].OneofWrappers = []any{
		(*PropagateEndnode_PrpAtt)(nil),
		(*PropagateEndnode_PrpDet)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cmd_propagate_endnode_proto_rawDesc), len(file_cmd_propagate_endnode_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cmd_propagate_endnode_proto_goTypes,
		DependencyIndexes: file_cmd_propagate_endnode_proto_depIdxs,
		MessageInfos:      file_cmd_propagate_endnode_proto_msgTypes,
	}.Build()
	File_cmd_propagate_endnode_proto = out.File
	file_cmd_propagate_endnode_proto_goTypes = nil
	file_cmd_propagate_endnode_proto_depIdxs = nil
}
